language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
install: npm install
before_script:
  - "pwd"
  - "ls"
  - "ln -s ~/achiever/app/ex.config.js ~/achiever/app/config.js"
script: npm run start
